"""Type stub for app.common.errors — exception hierarchy."""

class LSMError(Exception): ...
class WALCorruptError(LSMError): ...
class WALTruncateError(LSMError): ...
class EngineClosed(LSMError): ...
class MemTableFullError(LSMError): ...
class SnapshotEmptyError(LSMError): ...
class SkipListInsertError(LSMError): ...
class SkipListKeyError(LSMError): ...
class FreezeBackpressureTimeout(LSMError): ...
class ImmutableTableAccessError(LSMError): ...
class MemTableRestoreError(LSMError): ...
class CorruptRecordError(LSMError): ...
class SSTableWriteError(LSMError): ...
class SSTableReadError(LSMError): ...
class FlushError(LSMError): ...
class CompactionError(LSMError): ...
