"""Type stub for app.engine.config — runtime-mutable engine configuration."""

from pathlib import Path

from app.common.errors import LSMError

class ConfigError(LSMError): ...

class LSMConfig:
    def __init__(self, path: Path) -> None: ...
    def __getattr__(self, name: str) -> int | float | str: ...

    @property
    def is_dev(self) -> bool: ...
    @property
    def is_prod(self) -> bool: ...
    @property
    def max_memtable_bytes(self) -> int: ...
    @property
    def bloom_fpr(self) -> float: ...

    def set(
        self, key: str, value: int | float | str,
    ) -> tuple[int | float | str, int | float | str]: ...
    def to_dict(self) -> dict[str, int | float | str]: ...
    def to_json(self, indent: int = 2) -> str: ...

    @classmethod
    def load(
        cls,
        data_root: Path,
        config_path: Path | None = None,
    ) -> LSMConfig: ...
